--Consulta 1
--Listar funcionários sem o dígito inicial '8' e listar quais máquinas são usadas em quais projetos
SELECT CODIGO_FERRAMENTA, CODIGO_PROJETO
FROM FUNCIONARIO NATURAL JOIN PLANEJA NATURAL JOIN DESIGN NATURAL JOIN PROJETO
WHERE EXISTS (SELECT CODIGO_FUNCIONARIO
				FROM FUNCIONARIO F, UTILIZA U, REALIZA R
					WHERE F.CODIGO_FUNCIONARIO = U.CODIGO_FUNCIONARIO
					AND F.CODIGO_FUNCIONARIO = R.CODIGO_FUNCIONARIO) 
	AND UTILIZA.CODIGO_FUNCIONARIO = FUNCIONARIO.CODIGO_FUNCIONARIO 
	AND CODIGO_FUNCIONARIO NOT LIKE '8%'
ORDER BY 2;

--Consulta 2
--Listar 
SELECT CODIGO_FUNCIONARIO,CODIGO_ATV, AVG (NUM_HORAS)
FROM FUNCIONARIO F, ATIVIDADE A,UTILIZA U, REALIZA R
	WHERE EXISTS (SELECT NUM_HORAS FROM R, U  
		WHERE CODIGO_FUNCIONARIO = F.CODIGO_FUNCIONARIO
			AND U.CODIGO_FUNCIONARIO = F.CODIGO_FUNCIONARIO)
	AND R.CODIGO_ATV = A.CODIGO_ATV
	AND F.CODIGO_FUCNIONARIO = U.CODIGO_FUNCIONARIO 
	AND U.CODIGO_FUNCIONARIO = R.CODIGO_FUNCIONARIO
GROUP BY CODIGO_FUNCIONARIO, CODIGO_ATV
ORDER BY 3 DESC;

--Consulta 3
--Listar os funcionários que não estão na tabela PLANEJA 
 Consulta com o uso de operadores de conjuntos (UNION, INTERSECT ou MINUS)
 Ao menos 3 tabelas;
- Seleções sobre colunas que não pertençam às chaves primárias das tabelas;

SELECT CODIGO_FUNCIONARIO FROM FUNCIONARIO
MINUS
SELECT  CODIGO_FUNCIONARIO FROM PLANEJA;